### ISSUE TITLE
Speed up tests that rely on a real cassandra server

### ISSUE THREAD

**Issue by wallrj** [sky-uk/cassandra-operator#103]
Related to: https://github.com/sky-uk/cassandra-operator/issues/15

There are some tests that have to use a real cassandra cluster and these can be slow and resource intensive.
The official Cassandra:3.11.4 image takes at least 30 seconds to start up.
And it uses HEAP memory based on the available memory of the host machine rather than the Memory limit of the container.

There are few things that we can do to make it start faster:
 * `-Dcassandra.skip_wait_for_gossip_to_settle=0 -Dcassandra.load_ring_state=false`
 * https://medium.com/@saidbouras/running-integration-tests-with-apache-cassandra-42305dc260a6
 * https://github.com/saidbouras/cassandra-docker-unit
 * https://github.com/asarkar/url-shortener/blob/master/src/test/kotlin/org/asarkar/urlshortener/ApplicationTest.kt#L54

And we can limit the memory used by each C* node to, maybe, as little as 300Mi
 * https://opensourceconnections.com/blog/2013/08/31/building-the-perfect-cassandra-test-environment/

Or by having Cassandra calculate its own HEAP size based on the configured Kubernetes Limits:
 * https://github.com/GoogleCloudPlatform/cassandra-docker/pull/31

Also investigate what optimizations are used by CCM. I am able to start a 3-node cluster in CCM in less than 30 seconds and with around 300Mi for each node.

```
~/.local/bin/ccm create cluster1 -v 3.11.4  --vnodes -n 3
conf=( "concurrent_reads: 2" "concurrent_writes: 2" "rpc_server_type: hsha" "rpc_min_threads: 1" "rpc_max_threads: 1" "write_request_timeout_in_ms: 5000" "concurrent_compactors: 1" "compaction_throughput_mb_per_sec: 0" "key_cache_size_in_mb: 0" "concurrent_counter_writes: 4" "num_tokens: 4" "auto_snapshot: false" "enable_materialized_views: false" "internode_compression: none" "phi_convict_threshold: 16" "file_cache_size_in_mb: 1")
~/.local/bin/ccm updateconf "${conf[@]}" 
~/.local/bin/ccm start --jvm_arg="-Xmx48m -Xms32m -Xmn12m"
```

* The `updateconf` step may not be necessary.

**Comment by sebbonnet** [comment]
We should also look at scylladb which is meant to be a drop-in replacement for cassandra. It's got nodetool, cqlsh and should be more lightweight as written in C++.
https://www.scylladb.com/download/open-source/

**Comment by wallrj** [comment]
ScyllaDB has Scylla JMX Server: https://github.com/scylladb/scylla-jmx 
> Scylla JMX server implements the Apache Cassandra JMX interface for compatibility with tooling such as nodetool. The JMX server uses Scylla's REST API to communicate with a Scylla server.

Perhaps we could re-use this or  as inspiration  for our fake cassandra.
It might be that we can implement the correct JMX APIs in our fake and then use real jolokia and real nodetool.
This might be a better approach than trying to fake `nodetool`, `cassandra` and `jolokia`.

**Comment by wallrj** [comment]
Some startup time measurements with gossip and vnodes disabled and different soft memory limits:

`-Dcassandra.skip_wait_for_gossip_to_settle=0 -Dcassandra.load_ring_state=false -Dcassandra.initial_token=1 -Dcassandra.num_tokens=nil -Dcassandra.allocate_tokens_for_local_replication_factor=nil`

* ~7s (with 1G memory limit)
```
docker run --rm --volume $PWD/jolokia-jvm-1.4.0-agent.jar:/jolokia.jar:ro  --memory 1000m -e CASSANDRA_CGROUP_MEMORY_LIMIT=true -e JVM_EXTRA_OPTS="-javaagent:/jolokia.jar=host=0.0.0.0,port=8778,agentContext=/jolokia -Dcassandra.skip_wait_for_gossip_to_settle=0 -Dcassandra.load_ring_state=false -Dcassandra.initial_token=1 -Dcassandra.num_tokens=nil -Dcassandra.allocate_tokens_for_local_replication_factor=nil" -p 8778:8778 marketplace.gcr.io/google/cassandra:3.11 | fgrep -e 'Configuration location: file:/etc/cassandra/cassandra.yaml' -e 'Starting listening for CQL clients on /0.0.0.0:9042' -e JOINING
INFO  [main] 2019-06-05 11:06:04,653 YamlConfigurationLoader.java:89 - Configuration location: file:/etc/cassandra/cassandra.yaml
INFO  [main] 2019-06-05 11:06:10,767 StorageService.java:1483 - JOINING: Finish joining ring
INFO  [main] 2019-06-05 11:06:11,512 Server.java:156 - Starting listening for CQL clients on /0.0.0.0:9042 (unencrypted)...

```


* ~9.5s (with 300M memory)
```
docker run --rm --volume $PWD/jolokia-jvm-1.4.0-agent.jar:/jolokia.jar:ro  --memory 300m -e CASSANDRA_CGROUP_MEMORY_LIMIT=true -e JVM_EXTRA_OPTS="-javaagent:/jolokia.jar=host=0.0.0.0,port=8778,agentContext=/jolokia -Dcassandra.skip_wait_for_gossip_to_settle=0 -Dcassandra.load_ring_state=false -Dcassandra.initial_token=1 -Dcassandra.num_tokens=nil -Dcassandra.allocate_tokens_for_local_replication_factor=nil" -p 8778:8778 marketplace.gcr.io/google/cassandra:3.11 | fgrep -e 'Configuration location: file:/etc/cassandra/cassandra.yaml' -e 'Starting listening for CQL clients on /0.0.0.0:9042' -e JOINING
OpenJDK 64-Bit Server VM warning: MaxNewSize (409600k) is equal to or greater than the entire heap (153600k).  A new max generation size of 153536k will be used.
INFO  [main] 2019-06-05 11:07:59,709 YamlConfigurationLoader.java:89 - Configuration location: file:/etc/cassandra/cassandra.yaml
INFO  [main] 2019-06-05 11:08:07,268 StorageService.java:1483 - JOINING: Finish joining ring
INFO  [main] 2019-06-05 11:08:08,360 Server.java:156 - Starting listening for CQL clients on /0.0.0.0:9042 (unencrypted)...

```

* ~11s with 200M memory

```
docker run --rm --volume $PWD/jolokia-jvm-1.4.0-agent.jar:/jolokia.jar:ro  --memory 200m -e CASSANDRA_CGROUP_MEMORY_LIMIT=true -e JVM_EXTRA_OPTS="-javaagent:/jolokia.jar=host=0.0.0.0,port=8778,agentContext=/jolokia -Dcassandra.skip_wait_for_gossip_to_settle=0 -Dcassandra.load_ring_state=false -Dcassandra.initial_token=1 -Dcassandra.num_tokens=nil -Dcassandra.allocate_tokens_for_local_replication_factor=nil" -p 8778:8778 marketplace.gcr.io/google/cassandra:3.11 | fgrep -e 'Configuration location: file:/etc/cassandra/cassandra.yaml' -e 'Starting listening for CQL clients on /0.0.0.0:9042' -e JOINING
OpenJDK 64-Bit Server VM warning: MaxNewSize (409600k) is equal to or greater than the entire heap (102400k).  A new max generation size of 102336k will be used.
INFO  [main] 2019-06-05 11:09:07,534 YamlConfigurationLoader.java:89 - Configuration location: file:/etc/cassandra/cassandra.yaml
INFO  [main] 2019-06-05 11:09:16,773 StorageService.java:1483 - JOINING: Finish joining ring
INFO  [main] 2019-06-05 11:09:18,000 Server.java:156 - Starting listening for CQL clients on /0.0.0.0:9042 (unencrypted)...

```

**Comment by adamdougal** [comment]
Closing as we would rather the test be as realistic as possible.
