### ISSUE TITLE
Verify that fake Cassandra responds the same as real Cassandra

### ISSUE THREAD

**Issue by wallrj** [sky-uk/cassandra-operator#104]
See: https://pythonspeed.com/articles/verified-fakes/

If we're going to use a Fake / Stub Cassandra, we ought to have tests that ensure that it behaves the same as the real thing.

We could add a test suite that is run against both the real and the fake Cassandra.

We'd need to test the fake Jolokia behaviour and the fake nodetool behaviour.

See #32

**Comment by wallrj** [comment]
There are some existing projects that we might be able to use / re-use or learn from:
 * https://github.com/datastax/simulacron
 * https://www.scassandra.org/
 * https://www.testcontainers.org/modules/databases/cassandra/

**Comment by adamdougal** [comment]
Closing as we only use fake cassandra where it doesn't matter how Cassandra responds.
