### ISSUE TITLE
Delete custom configmap on cluster deletion

### ISSUE THREAD

**Issue by sebbonnet** [sky-uk/cassandra-operator#114]
When creating a cluster, clients can optionally create a custom configuration to override Cassandra configuration file. By convention the configmap is expected to be named after the cluster,
However when the cluster is deleted, the configmap is expected to be deleted manually.
There is no reason to keep the custom config map once the cluster is deleted, so I think we should also delete the custom configmap on cluster deletion.

When a cluster is created, we should add the ownerRef reusing the same mechanism as we've done in #100

**Comment by adamdougal** [comment]
Closing as we feel it is wrong for the operator to delete a resource it does not manage.
