### ISSUE TITLE
Intermittent build failure: Could not GET 'https://repo.maven.apache.org/maven2/org/apache/cassandra/cassandra-all/3.11.2/cassandra-all-3.11.2.pom'. Received status code 403 from server: Forbidden

### ISSUE THREAD

**Issue by wallrj** [sky-uk/cassandra-operator#141]
https://travis-ci.com/sky-uk/cassandra-operator/jobs/211057861#L1306

```
[31mFAILURE: [39m[31mBuild failed with an exception.[39m[0K
[0K
* What went wrong:
Could not resolve all files for configuration ':cassandra-bootstrapper:seed-provider:compileClasspath'.
[33m> [39mCould not resolve org.apache.cassandra:cassandra-all:3.11.2.
  Required by:
      project :cassandra-bootstrapper:seed-provider
   [33m> [39mCould not resolve org.apache.cassandra:cassandra-all:3.11.2.
      [33m> [39mCould not get resource 'https://repo.maven.apache.org/maven2/org/apache/cassandra/cassandra-all/3.11.2/cassandra-all-3.11.2.pom'.
         [33m> [39mCould not GET 'https://repo.maven.apache.org/maven2/org/apache/cassandra/cassandra-all/3.11.2/cassandra-all-3.11.2.pom'. Received status code 403 from server: Forbidden

* Try:
Run with [1m--stacktrace[m option to get the stack trace. Run with [1m--info[m or [1m--debug[m option to get more log output. Run with [1m--scan[m to get full insights.
```

I found this possibly related issue: https://github.com/gradle/gradle/issues/4107

**Comment by wallrj** [comment]
Travis CI servers may have been blacklisted by Maven Central. 
It's happened before:
 * https://github.com/travis-ci/travis-ci/issues/10053

**Comment by wallrj** [comment]
Another example: 
 * https://github.com/travis-ci/travis-ci/issues/6593

**Comment by wallrj** [comment]
There's an ongoing discussion at https://travis-ci.community/t/continuous-maven-repo-403/3908/2

**Comment by wallrj** [comment]
Issue reported to Maven Central: https://issues.sonatype.org/browse/MVNCENTRAL-4985

**Comment by sebbonnet** [comment]
Judging by the number of similar issues reported on Maven central, it seems that this is a fairly common issue. Although we get a 403 Forbidden, I was expecting to see a message stating clearly that the Travis IP had been blacklisted as reported [MVNCENTRAL-3799](https://issues.sonatype.org/browse/MVNCENTRAL-3799) or [MVNCENTRAL-3798](https://issues.sonatype.org/browse/MVNCENTRAL-3798).
It's quite possible travis CI is getting blacklisted, as documented here: https://central.sonatype.org/articles/2018/Sep/06/403-forbidden-error-from-central/

I wonder if it would be worth trying other repositories like jCenter which should be a copy of maven central or even Google's maven repository mirror (https://maven-central.storage-download.googleapis.com/repos/central/data/)

**Comment by sebbonnet** [comment]
Didn't mean to close it right away. 
I think we need to wait for a few build and for feedback on the issue @wallrj raised with MVNCENTRAL.

This site has a list of maven public repo: https://www.deps.co/guides/public-maven-repositories/
Like I said above we could try switching to either jcenter or google's maven mirror to see if that helps.
I don't think having multiple repositories would work as gradle choose one repository to download the artifacts from for each module - in other words there is no fallback repository to download the artifacts from. See https://docs.gradle.org/current/userguide/introduction_dependency_management.html#sec:dependency_resolution

**Comment by sebbonnet** [comment]
The #142 merge to master showed 403 errors for different artifacts across all the jobs: https://travis-ci.com/sky-uk/cassandra-operator/builds/116986714
Travis NAT IPs are being whitelisted as per the last update in https://issues.sonatype.org/browse/MVNCENTRAL-4985

**Comment by juniocezar** [comment]
Keep having a similar issue, but with the message: Access Denied to maven central. [builds#117055303](https://travis-ci.com/juniocezar/Value-Range-Analysis/builds/117055303). It seems not all NAT IPs where whitelisted so far.

**Comment by wallrj** [comment]
Thanks @juniocezar I found there are some more IP addresses which were not included in `nat.travisci.net`. See:
 * https://issues.sonatype.org/browse/MVNCENTRAL-4985
 * https://travis-ci.community/t/continuous-maven-repo-403/3908/10

**Comment by wallrj** [comment]
MVNCENTRAL report that all Travis NAT IPs have now been whitelisted: https://issues.sonatype.org/browse/MVNCENTRAL-4985?focusedCommentId=732346&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-732346

**Comment by wallrj** [comment]
I haven't seen this failure for a week now. Closing.
