### ISSUE TITLE
Move cluster update validation to the validation package

### ISSUE THREAD

**Issue by wallrj** [sky-uk/cassandra-operator#148]
In #139 we added a validation package for validating new Cassandra clusters.
Next we need to add functions to validate cluster updates.
Dissallow all updates by default and allow only the modifications that we support in the operator.

**Comment by sebbonnet** [comment]
Invalid cluster updates are rejected in https://github.com/sky-uk/cassandra-operator/blob/v0.70.1-alpha.3/cassandra-operator/pkg/operator/operations/adjuster/adjuster.go#L199, so this work would look into exposing this validation so that it can also be invoked in the webhook on updates
