### ISSUE TITLE
Define benchmark to compare performances of operator-managed vs VM clusters

### ISSUE THREAD

**Issue by sebbonnet** [sky-uk/cassandra-operator#155]
Rather than coming up with our own benchmark we should look at public benchmarks that have been used in the past to test Cassandra. Two immediately come into mind: [YCSB](https://github.com/brianfrankcooper/YCSB) and [NdBench](https://github.com/Netflix/ndbench)

**Comment by sebbonnet** [comment]
### End Point (YCSB)

End Point was commissioned by DataStax in 2013 to conduct a retest of NoSQL database including Cassandra. Their white paper is available here: http://www.datastax.com/wp-content/themes/datastax-2014-08/files/NoSQL_Benchmarks_EndPoint.pdf

**Keypoints**
- Stragegy: 
  - Multiple clients on their own AWC EC2 c3.xlarge run various YCSB workloads. Each client targetted its own Cassandra instance
  - A customised version of https://github.com/joshwilliams/YCSB was used
  - Workloads A, B and F were used with custom parameters and 2 additional custom workloads were created. Other parameters were also adjusted at runtime.
  - An initial data set was loaded - we have no details of that
  - Each workload was run on all clients in parallel until 9 millions operations were achieved for up to 1hour max 
  - The next workload wasn't started until all side effects of the previous workload were complete (e.g. compactions)
  - Workfloads tests were repeated against 1,2,4,8,16 and 32 Cassandra-node clusters
  - YCSB results, essentially operations/secs and average latency, were aggregated from each client
- Cassandra: 
  - 2.1.0 running on AWS EC2 i2.xlarge instances
  - Ubuntu 14.04 LTS AMI in HVM virtualization mode, customized with Oracle Java 7
  - A single keyspace using SimpleStrategy and RF 1 was used
  - The keyspace had a single table with blob fields - the same as the example given in YCSB https://github.com/brianfrankcooper/YCSB/tree/master/cassandra
  - Custom cassandra.yaml, but I assume everything else comes with the default Cassandra install

**Conclusion**
Although their tests is well described, it won't be possible to apply their test setup as there is a significant amount of customisation (custom YCSB, custom workload, custom test script optmising parameters at runtime) that we have very little to no visibility on.
Besides their test is not representative of a production workload, but more geared towards achieving the highest throughput/latency out of a cluster - their setup is not rack aware, using RF=1 and a single table with blobs.

**Comment by sebbonnet** [comment]
### Instagram (NDBench)

Instagram have their own Cassandra storage engine which they maintain in a separate Cassandra fork called Rocksandra. They used NDBench to compare its performance with Cassandra. Blog: https://instagram-engineering.com/open-sourcing-a-10x-reduction-in-apache-cassandra-tail-latency-d64f86b43589 (march 2018)

**Keypoints**
- Strategy:
  - 4 client nodes on their own EC2 instances running NDBench workload
  - different custom AMI used for client and Cassandra nodes - we have no details on how this was built
  - use the default NDBench db schema (1 table of 4 text columns of which 1 is primary key), with NetworkTopologyStrategy and RF=1
  - initial data-set of 250MB loaded
  - measured avg, p99 and p999 read/write latencies
  - benchmark framework is open-sourced. It uses AWS cloudformation to setup the client nodes and the target Cassandra cluster. 
- Cassandra:
  - 3.0 running on AWS EC2 i3.xlarge (although their blog talks about i3.8xlarge)
  - 3-node cluster with 1 seed
  - default cassandra.yaml, but heap size set to 1/4 of system memory 

**Conclusion**
The benchmark framework is a good idea to make it easy for anyone to try reproducing the results.
However here again the data model and cluster setup is not representative of a production setup but geared towards achieving lowest latencies.

**Comment by sebbonnet** [comment]
Given that we're not seeing any public benchmarks that is representative enough of a production setup, we will look into implementing our own based on either YCSB or NDBench.

**Comment by sebbonnet** [comment]
### Custom benchmark

**Strategy**

- Find a workload that is stretching our cluster the most in terms of system resource usage
  - highest read/write throughput 
  - longest queries scanning multiple records
If we were to draw a comparison with YCSB workloads I think the above would best map to:
    - update heavy workload (Workload A) with a read/write ration: 50/50
    - read mostly workload (Workload B) with a read/write ratio: 95/5
    - short ranges workload (Workload E)
- Identify the queries used, volumes and data model including keys distribution
- Create a matching db schema for the test bed
- Bootstrap a small Cassandra cluster
  -  Typical production cluster have nodes spread across multiple racks to achieve higher resiliency. So we should start with a minimum of 6-node spread across 3 racks with 1 seed per rack and RF=3 to be able to sustain one node outage at LOCAL_QUORUM.
  - Choose disk type and size to make ensure enough IOPS to support the load 
- Scale the cluster as small as possible
   - we want to see performance degrading when load > peak load - _perhaps 20% above peak?_
- Warmup the cluster by loading data long enough to allow JVM warmup
  - _would 1min be enough or is it best to aim for a number of records matching prod load?_ 
- Run workload one after the other
  - Ramp-up load progressively to simulate prod pattern
  - Chose run duration to ensure we have a dataset big enough that it doesn't fit in memory. _If we have small nodes, how long would it take to load enough data to ensure the dataset no longer fits in memory?_
  - Wait long enough in between workloads to avoid the impact of compactions on the next test run. _Need to check if this is practical as it could take hours_
  - _Do we want to drop the host page cache too?_ My initial reaction is no as there could be more than one cache layer and we would have no guarantee that the cleanup happened. 
  - A safer mechanism would be to run different workloads on a fresh cluster every time.

**Comment by wallrj** [comment]
You may have read them already but ScyllaDB have some good pages on benchmarking with some links to tools, but no workloads (afaics):
 * https://docs.scylladb.com/operating-scylla/benchmarking-scylla/
 * https://github.com/scylladb/scylla/wiki/Benchmarking-Tutorial

**Comment by sebbonnet** [comment]
Thanks @wallrj - ScyllaDB actually published a benchmark here (which I hadn't seen): https://www.scylladb.com/product/benchmarks/aws-i3-metal-benchmark/. 

It's pretty well detailed and even gives the cassandra configuration and cassandra-stress commands that were used. Their test preloads about 6% of the data and their R/W queries use up to 38 billions partitions. Their dataset doesn't fit in memory (700GB per node) and they do replicate at RF=3 and query at quorum which is a good thing. 
However the data model used, being the default one in cassandra-stress, is not representative of a production data model: there are no clustering columns, blob only columns.
I also have to admit that a 40-node i3.4xlarge (16 CPU, 122GB RAM) cluster is much bigger than I ever imagine we'd use! I was looking for a much more reasonable workload as long as we can prove it scales linearly and not trying to find the limits of Cassandra as a concept.

**Comment by adamdougal** [comment]
Closing as we don't feel the effort is going to give us much value.
