### ISSUE TITLE
Updating racks waits indefinitely when pod fails to create

### ISSUE THREAD

**Issue by sebbonnet** [sky-uk/cassandra-operator#180]
### Is your feature request related to a problem? Please describe
When creating a statefulset we need to cater for scenarios where the pod(s) cannot be created for whatever reasons - e.g. insufficient resources, insufficient privileges.
At the moment the operator waits forever for the rack changes to be applied (see `accessor#WaitUntilRackChangeApplied`). As we only allow 1 queued operation per cluster, this  means that the Cassandra definition cannot be updated to rectify the problem (e.g. lowering resources requirements), leaving the user with no choice but restart the operator in order to apply the new Cassandra definition.

### Describe the solution you'd like
I think we need to distinguish cases where the pod creation fails due to an invalid definition (e.g. memory requests > limits) or due to external factors (insufficient resource, privileges).
- invalid Cassandra definition according to Kubernetes: we should ideally catch that upfront when validating Cassandra updates. However this may not always be possible, but we should at least try to identify the affected scenarios.
- invalid Cassandra definition due to human error: when for instance the wrong storage class was used or too much resource has been requested. In this case we would want to be able to amend the Cassandra definition - this would mean somehow cancelling the current update. Perhaps we could consider cancelling the current update if a new update has arrived or find a more deterministic way (perhaps via annotation?) to inform the operator to cancel the current operation?  
- valid Cassandra definition, but the environment cannot meet the requirements. For instance, they are insufficient resources or privileges in the cluster to accommodate the requirements. In this case, it is probably the right thing to do let the operator wait indefinitely, as we would expect the environment to be changed to satisfy the requirements in the Cassandra definition

### Additional context
This issue was found when trying to create a cluster with invalid pod resources where the memory limit was lower than the requested limit. Even though this is a scenario we should catch upfront when validating the Cassandra specs, there are other similar scenarios where the pod will fail to create.

**Comment by alangibson01** [comment]
> invalid Cassandra definition due to human error: when for instance the wrong storage class was used or too much resource has been requested. In this case we would want to be able to amend the Cassandra definition - this would mean somehow cancelling the current update. Perhaps we could consider cancelling the current update if a new update has arrived or find a more deterministic way (perhaps via annotation?) to inform the operator to cancel the current operation?

Cancellation - I don't think we want to do anything specific for that. The existence of a new version of the resource could act as a signal that a current "stuck" operation should be cancelled. Of course, that opens the question of how we determine a "stuck" operation.

**Comment by alangibson01** [comment]
I've been thinking about this a bit more and I'm not sure there's a reliable way to determine the different reasons that an operation may be stuck waiting for a stateful set to completely start up. It's probably a better idea if, during the wait loop, we check to see if a later `resourceVersion` of the Cassandra spec now exists, and if so, stop the current round of updates immediately. The new version of the Cassandra spec will automatically trigger another reconciliation, which may be able to resolve the cause of the stuckness.
