### ISSUE TITLE
How your perform backup/restore on K8S ?

### ISSUE THREAD

**Issue by ahmedjami** [sky-uk/cassandra-operator#225]
Hi everyone,

For those who have deployed Cassandra on K8S, could you share your way of doing a backup and especially the restore?
sky-uk has developed Cassandra-snapshot for taking snapshot but I want to know how do you perform a copy to another location (S3 for example) and how you perform a restore if necessary.

I found 

Thanks

**Comment by sebbonnet** [comment]
Thank you for your interest @ahmedjami 

As you mentioned we've developed a mechanism to automatically schedule snapshots by means of Kubernetes cron job - this is described here: https://github.com/sky-uk/cassandra-operator/wiki/Making-Snapshots.

Today the snapshot data is left on the Cassandra pods and if you want to restore to a snapshot at a given point in time you have to follow the [Restoring from local nodes](https://docs.datastax.com/en/dse/5.1/dse-admin/datastax_enterprise/operations/opsBackupSnapshotRestore.html#Restoringfromlocalnodes ) mechanism.
If you want to have the snapshot data on remote storage, you will need to implement your own solution for now.  We did consider pushing the data to S3 storage, but this is not on our roadmap at the moment.

**Comment by ahmedjami** [comment]
Thanks @sebbonnet 

that's I will do :)
