### ISSUE TITLE
Metrics always reading from the same node

### ISSUE THREAD

**Issue by chuckydev** [sky-uk/cassandra-operator#231]
### What is the bug being reported?

A log was observed when running the operator, which implied the metrics were being fetched from the same node. This implies that the IP lookup is not working as expected and we are resorting to fetching metrics from the same node.
```
time="2020-10-21T19:44:05Z" level=info msg="No pods with IP addresses found for cluster ccl-prod.ccl-cassandra. Falling back to the cluster service name for jolokia url."
```
The original issue is #3. This appears to have occured since the removal of the app label from each cassandra pod.

### What would be the expected behavior?
The IP Lookup to search for the correct label and return a list of IPs. This then allows the metrics to be fetched from a random node.

### If repeatable, how can we reproduce this issue?
I believe this should exist in versions since the removal of the app label

**Comment by adamdougal** [comment]
Need to chat to @chuckydev to get more of an understanding of what this is about.

**Comment by chuckydev** [comment]
This can be closed as the tag we look up on each operator pod has been corrected
