### ISSUE TITLE
Investigate and review the behaviour of OPERATOR_IMAGE

### ISSUE THREAD

**Issue by Bez625** [sky-uk/cassandra-operator#259]
## Motivation
OPERATOR_IMAGE is a reserved environment variable that is utilised by the cassandra-operator. The behaviour driven by this variable seems to extend further than the documentation - for example there is logic to extract the docker repository from this for use in default images. The motivation is to assess the benefit this variable offers and clearly document the behaviour it triggers.

## Requirements
- List the behaviours triggered by / linked to this variable.
- Assess if this behaviour is beneficial.
- Remove behaviours that offer no benefit
- If the variable remains ensure it is appropriately named 
- Fully document the resulting behaviours in the wiki.

### Additional context
We should aim to answer questions such as:
- What happens if the variable is not supplied?
- What happens if the variable supplied is empty?

---- To be filled in by Assignee -----
## Tasks/Feature Set
List tasks/features in order to meet the requirements listed above

**Comment by amiralibazazi** [comment]
Upon brief investigation, it looks like the only thing this variable is used for is extracting the image `version` and the `repositoryPath` of the docker image, found on [these lines in main.go](https://github.com/sky-uk/cassandra-operator/blob/master/cassandra-operator/cmd/operator/main.go#L93). 
These two fields are then used in reconciliiation in `reconcile.go`

It seems like a slightly roundabout way to pass in that information, I haven't deep dug enough into the implementation to undersatnd how the fields are relevant. It seems they are necessary but at the very least could probably be passed in a dfferent way
