### ISSUE TITLE
Log file system management for cassandra nodes

### ISSUE THREAD

**Issue by sebbonnet** [sky-uk/cassandra-operator#29]
To ensure that cluster spun with the default configuration are created with a sensible file system strategy that limits the logs size and avoids filling up the docker volume.

**Logs** 
- Logs should be send to STDOUT only by default, as limiting the number / size of log files would do nothing to prevent against I/O starvation. However we should give the option to clients to send logs to a dedicated EBS volume 
- GC logs should be send to STDOUT by default too
- Logs should be sent to a dedicated volume when the feature is enabled or emptyDir as a fallback, as emptyDir would still be better than writting to the docker volume 
  - using emptyDir would mean the host I/O would be shared with the other pods on the same host and would make the cassandra pod candidate for eviction once pod eviction policy is implemented
  - using the same EBS volume as for the data could affect Cassandra performances as the I/O throughput would be shared. In the case of AWS EBS where the IOPS depends on disk size, it would also make it difficult to define the disk size as logs throughput is less predictable than client requests TPS

**Temp files**  
- potentially mount /tmp on emptyDir tmpfs

**Comment by alangibson01** [comment]
After discussion, we've decided that the best way to address this is by adding some wiki documentation describing why and how logs can be written safely.
