### ISSUE TITLE
Pod liveness and readiness probes frequently start JVMs, consuming CPU

### ISSUE THREAD

**Issue by alangibson01** [sky-uk/cassandra-operator#30]
Cassandra pod liveness and readiness probes both use `nodetool` in order to perform their checks. This is rather heavyweight, as it requires starting up a JVM. Given we run 2 liveness checks and 4 readiness checks a minute, this demands rather a lot of CPU. Looking at the CPU metrics for the cluster belonging to verification-app in dev, we can see that CPU usage hovers around 50% even when the cluster is at rest:

![screenshot from 2018-10-16 15-01-26](https://user-images.githubusercontent.com/20461485/47022452-6dd68200-d155-11e8-8354-9c5fbd1c8ef8.png)

**Comment by wallrj** [comment]
Here's how we tackled this in Navigator: https://github.com/jetstack/navigator/pull/170

**Comment by sebbonnet** [comment]
Nice to see you cracked this problem before :)
I think we both agree that using jolokia as a nodetool replacement sounds like the right approach.

As we have jolokia installed on cassandra nodes already, I imagined initially that we could simply use a curl command to find a node status. However as the information to determine the node state (e.g. normal) is scattered across different mbean attributes I think we will need write a small tool to combine the results from multiple mbean responses.

To illustrate my point:
- node UP: 
```
curl localhost:7777/jolokia/read/org.apache.cassandra.db:type=StorageService/LiveNodes | grep <pod-ip>
```
- node normal: 
```
!curl localhost:7777/jolokia/read/org.apache.cassandra.db:type=StorageService/JoiningNodes | grep -v <pod-ip> && \
!curl localhost:7777/jolokia/read/org.apache.cassandra.db:type=StorageService/LeavingNodes | grep -v <pod-ip> && \
!curl localhost:7777/jolokia/read/org.apache.cassandra.db:type=StorageService/MovingNodes | grep -v <pod-ip> && \
!curl localhost:7777/jolokia/read/org.apache.cassandra.db:type=StorageService/UnreachableNodes | grep -v <pod-ip> &&
```

We already use jolokia to expose cluster level metrics in the operator (https://github.com/sky-uk/cassandra-operator/blob/master/cassandra-operator/pkg/metrics/metrics.go#L85), so it would be nice it we could extract that logic and use it in the "probe" tool. We'll have to see whether it's worth the effort.

So i think the plan of action for me would be:
- extract the jolokia nodestatus logic to its own module
- update `cassandra-bootstrapper` to copy the library somewhere on the node - probably need to mount a different volume, as `extra-lib` is meant to contain additional jars loaded on cassandra classpath
- invoke the library from the pod liveness/readiness probes

@alangibson01 Any thoughts?
