### ISSUE TITLE
Define style guide for java modules

### ISSUE THREAD

**Issue by sebbonnet** [sky-uk/cassandra-operator#46]
### Is your feature request related to a problem? Please describe
There are no style guide defined for the java modules meaning that enforcing code standard happens too late once the PR is submitted and requires a human to review the style which is both tedious and inconsistent.  

 ### Describe the solution you'd like
Add checkstyle as part of the build for both our java modules.
Perhaps try to harvest bits we like from https://github.com/thelastpickle/cassandra-reaper/blob/master/src/server/checkstyle.xml

**Comment by wallrj** [comment]
This could be executed by `make -C cassandra-bootstrapper verify` which I added in #68
