### ISSUE TITLE
Migrate from dep to Go modules

### ISSUE THREAD

**Issue by kragniz** [sky-uk/cassandra-operator#60]
The project currently uses `dep` to manage go dependencies. Go modules are generally more pleasant to use, but require Go 1.11.

Migrate from dep to Go modules at some point after moving to Go 1.11 or newer.

**Comment by sebbonnet** [comment]
I haven't used go modules yet, but the fact that dep management is integrated in standard `go build` and `go test` commands sound like a good thing.
We would need to find replacement for `dep status` too which we use to pass the list of vendor dependencies to the tool checking licence compliance.

Travis CI already builds using go 1.11

**Comment by sebbonnet** [comment]
Work done in #86
