### ISSUE TITLE
`make fmt` should report rather than fix mis-formatted code

### ISSUE THREAD

**Issue by wallrj** [sky-uk/cassandra-operator#69]
Currently `make fmt` is run as a dependency of `make check` and `make verify` but it modifies the code in-place rather than reporting the formatting changes.

This means that our CI system is testing and building different code than is in the repo.

It'd be better to have `make fmt` report the changes that are required and fail if changes are required.

Leave it to the developer  to run go fmt manually.

Related to #68 and #66

**Comment by sebbonnet** [comment]
Should be a simple case of using `gofmt` instead of `go fmt`
