### ISSUE TITLE
API hardcodes service accounts

### ISSUE THREAD

**Issue by kragniz** [sky-uk/cassandra-operator#73]
The API types.go currently hardcodes `NodeServiceAccountName` and `SnapshotServiceAccountName`. We should think about generating separate service accounts per managed cassandra cluster.

Related to #33.

**Comment by sebbonnet** [comment]
On second look, `cassandra-node` and `cassandra-snapshot` are both using a `RoleBinding` and so namespaced. I don't think permissions need to be more granular than that.
Even if the operator is deployed to watch over multiple namespaces, both these roles can remain namespaced and have a corresponding `RoleBinding` created in the namespaces where the clusters need to be created.
