### ISSUE TITLE
Remove Pod.LivenessProbe and Pod.ReadinessProbe from the API

### ISSUE THREAD

**Issue by wallrj** [sky-uk/cassandra-operator#75]
Part of #33 

It's difficult to think of a situation where a user will need to override the Liveness and Readiness probes for the Cassandra nodes.
And since these are so important to determining the health of the cluster and in controlling the operations that the operator performs on the cluster, it seems like these ought to be hard configured with settings that are known to work with the operator.

**Comment by alangibson01** [comment]
I don't think we'd ever want a situation where liveness or readiness probes were disabled, or where what a probe does is modified. However, I can imagine that users may wish to tweak how frequently the probes run or how many failures they are willing to tolerate before a pod gets rescheduled.

**Comment by sebbonnet** [comment]
Cassandra start up time would vary depending on the resource the pod has been allocated and the storage type used. I don't think we can come up with a generic enough set of values that would cover all cases and so I think it's best if we continue to expose these properties in the API.

**Comment by wallrj** [comment]
I see now that this is also important for use in tests, where the thresholds can be lowered for tests that use the fake cassandra.
