### ISSUE TITLE
Consider making Snapshot a top-level resource

### ISSUE THREAD

**Issue by kragniz** [sky-uk/cassandra-operator#81]
Consider making Snapshot a top-level resource, operating more like a kubernetes `Job`.

A `SnapshotSchedule` resource could then layer on top to periodically create Snapshots

This would allow more flexibility in managing snapshotting, for example different schedules for individual keyspaces.

Also allow better error reporting via `Snapshot.Status`.

**Comment by alangibson01** [comment]
Could you sketch out how you envisage the API looking? I'm not sure I understand what you mean about `SnapshotSchedule` layering on top.

Another thought is that if we split snapshots out from the cluster spec, we'd need to account for the possibility of a cluster being deleted but snapshots which reference it still existing.

**Comment by wallrj** [comment]
@alangibson01 to be honest, @kragniz and I were doing a lot of hand waving at this stage, but I think  we were being influenced by other Backup APIs we've seen. For example:
* https://github.com/heptio/velero/blob/master/pkg/apis/velero/v1/backup.go
* https://github.com/heptio/velero/blob/master/pkg/apis/velero/v1/schedule.go

And: 
 * https://github.com/coreos/etcd-operator/blob/master/doc/user/walkthrough/backup-operator.md

A Snapshot existing without a cluster may be a useful thing, if the cluster has been accidentally deleted, but the data still exists on PVs.

**Comment by wallrj** [comment]
@kragniz pointed out this Cassandra backup API https://github.com/instaclustr/cassandra-operator/blob/master/doc/backup_restore.md  which we could examine for ideas.

**Comment by sebbonnet** [comment]
Closing as explained here: https://github.com/sky-uk/cassandra-operator/pull/84#discussion_r285077126
