### ISSUE TITLE
Add OpenAPI validation to CRD resource 

### ISSUE THREAD

**Issue by kragniz** [sky-uk/cassandra-operator#82]
See https://v1-10.docs.kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/#validation

We should be able to generate this automatically using [controller-gen](https://github.com/kubernetes-sigs/controller-tools/tree/master/cmd/controller-gen).

**Comment by kragniz** [comment]
Going to wait for https://github.com/kubernetes-sigs/controller-tools/pull/186 to merge.

**Comment by sebbonnet** [comment]
Closed by https://github.com/sky-uk/cassandra-operator/issues/82
